---

- name: Add review.opencontrail.org remote
  command: git remote add gerrit https://review.opencontrail.org/Juniper/{{ item }}
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/{{ item }}"
  failed_when: false
  with_items:
    - contrail-controller
    - contrail-build
    - contrail-vrouter
    - contrail-sandesh
    - contrail-generateDS
    - contrail-common
    - contrail-analytics
    - contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for adding remotes
    - skip_ansible_lint

- name: Fetch all remotes
  command: git fetch --all
  args:
    chdir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/{{ item }}"
  with_items:
    - contrail-controller
    - contrail-build
    - contrail-vrouter
    - contrail-sandesh
    - contrail-generateDS
    - contrail-common
    - contrail-analytics
    - contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for fetching
    - skip_ansible_lint

